# Generated by Django 3.2.5 on 2021-07-06 09:30

from django.db import migrations, models
import enum


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name=enum.unique)),
                ('quote', models.CharField(max_length=400)),
                ('speaker', models.CharField(max_length=40)),
                ('pic', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
